In [1]:
import quippy
import einops
import numpy as np

In [2]:
from moldiff.utils import initialize_mol

In [3]:
mol = initialize_mol("C6H6")

In [4]:
from moldiff.sampling import SOAPSimilarityModel

/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
training_data = [initialize_mol("C6H6"), initialize_mol("CH4"), initialize_mol("CH3OH"), initialize_mol("H2O")]

In [6]:
scorer = SOAPSimilarityModel(training_data=training_data)

In [7]:
scorer.reference_embeddings.shape

(26, 547)

In [13]:
test_mol = initialize_mol("C6H6")
test_mol.set_positions(
    test_mol.positions + 0.05*np.random.normal(size=test_mol.get_positions().shape)
)
print(test_mol.positions)
scorer(test_mol,t=0)

[[-0.00774872  1.34670471  0.02774704]
 [ 1.20695149  0.69266141 -0.03367271]
 [ 1.33196729 -0.76574677  0.01200852]
 [-0.02303214 -1.50604272 -0.01608922]
 [-1.23638801 -0.59750931 -0.09449511]
 [-1.19751762  0.68749614 -0.06661533]
 [ 0.03456925  2.49043929  0.01998897]
 [ 2.09045362  1.24693427 -0.09574844]
 [ 2.20072728 -1.26048729  0.01475237]
 [-0.0601745  -2.55494833 -0.08434789]
 [-2.15218245 -1.21607565  0.07508577]
 [-2.12708108  1.25766503 -0.03161351]]


array([[-0.05820536,  0.99640071, -0.06162596],
       [-0.97498333,  0.21831973, -0.04176128],
       [ 0.98575358,  0.16762384, -0.01386068],
       [-0.02940119, -0.9968267 , -0.07397371],
       [ 0.94766146,  0.29474899,  0.12272238],
       [ 0.07132759,  0.99631385, -0.04765594],
       [ 0.27817571, -0.96041585,  0.01482118],
       [-0.73858554, -0.67413782,  0.00544075],
       [ 0.95016757,  0.31165214,  0.00738452],
       [ 0.01192176,  0.99652597, -0.08242489],
       [-0.97140796,  0.21649234,  0.09745583],
       [ 0.65910822,  0.75130639, -0.0333926 ]])

In [9]:
test_mol = initialize_mol("C6H6")
scorer(test_mol,t=0)

array([[-1.21554972e-04, -9.99999993e-01,  0.00000000e+00],
       [ 8.11689500e-01, -5.84089167e-01,  0.00000000e+00],
       [ 9.99976167e-01,  6.90395161e-03,  0.00000000e+00],
       [ 9.02687833e-01, -4.30296032e-01,  0.00000000e+00],
       [-9.51294471e-01, -3.08283683e-01,  0.00000000e+00],
       [ 4.84629798e-02, -9.98824979e-01,  0.00000000e+00],
       [-1.05361278e-01,  9.94434010e-01,  0.00000000e+00],
       [ 6.08428310e-01,  7.93608840e-01,  0.00000000e+00],
       [ 5.30749750e-01,  8.47528585e-01,  0.00000000e+00],
       [-2.97233838e-01,  9.54804716e-01,  0.00000000e+00],
       [ 6.15889871e-02,  9.98101596e-01,  0.00000000e+00],
       [ 2.78257233e-01, -9.60506591e-01,  0.00000000e+00]])